-- Auto-generated by scripts/generate-seed.mjs. Do not edit by hand.

insert into public.categories (id, slug, name, icon, sort_order) values
  (1, 'hair-salon', 'Hair Salon', 'cut-outline', 0),
  (2, 'barbershop', 'Barbershop', 'man-outline', 1),
  (3, 'nail-salon', 'Nail Salon', 'color-palette-outline', 2),
  (5, 'waxing-salon', 'Waxing Salon', 'leaf-outline', 3),
  (6, 'skincare-salon', 'Facials & Skincare', 'sparkles-outline', 4),
  (7, 'makeup-salon', 'Makeup Studio', 'rose-outline', 5),
  (8, 'bridal-salon', 'Bridal Salon', 'heart-outline', 6);
select setval('public.categories_id_seq', 7);

insert into public.venues (id, slug, name, description, category_id, address, area, city, country, rating_avg, rating_count, is_featured, is_new, is_trending, highlights) values
  ('00000000-0000-4000-8000-000000000002', 'the-fade-room', 'The Fade Room', 'A modern barbershop for the modern gentleman. Precision fades, classic cuts, hot towel shaves and beard sculpting from award-winning barbers in a relaxed, stylish space.', 2, 'Prince Turki St', 'Corniche', 'Al Khobar', 'Saudi Arabia', 5, 114, true, false, false, array['Instant confirmation', 'Pay by app', 'Walk-ins welcome']::text[]);
insert into public.venue_images (venue_id, url, sort_order) values
  ('00000000-0000-4000-8000-000000000002', 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=1200&q=80&auto=format&fit=crop', 0),
  ('00000000-0000-4000-8000-000000000002', 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&q=80&auto=format&fit=crop', 1),
  ('00000000-0000-4000-8000-000000000002', 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=1200&q=80&auto=format&fit=crop', 2);
insert into public.services (id, venue_id, name, description, group_name, duration_minutes, price_cents, currency, discount_pct, is_featured, sort_order) values
  ('00000000-0000-4000-9002-000000000001', '00000000-0000-4000-8000-000000000002', 'Skin Fade + Beard Sculpt', 'Our signature combo: a razor-sharp skin fade with a fully sculpted beard finish.', 'Featured', 60, 12000, 'SAR', 10, true, 0),
  ('00000000-0000-4000-9002-000000000002', '00000000-0000-4000-8000-000000000002', 'Classic Haircut', 'Consultation, cut and style with premium products.', 'Featured', 45, 9000, 'SAR', 0, true, 1),
  ('00000000-0000-4000-9002-000000000003', '00000000-0000-4000-8000-000000000002', 'Hot Towel Shave', 'Traditional straight-razor shave with hot towels and soothing balm.', 'Featured', 30, 7000, 'SAR', 0, true, 2),
  ('00000000-0000-4000-9002-000000000004', '00000000-0000-4000-8000-000000000002', 'Beard Trim & Line Up', 'Precision beard shaping with sharp lines and natural fades.', 'Beard', 25, 5000, 'SAR', 0, false, 3),
  ('00000000-0000-4000-9002-000000000005', '00000000-0000-4000-8000-000000000002', 'Kids Haircut', 'Patient, friendly cuts for the little gentlemen.', 'Hair', 30, 6000, 'SAR', 0, false, 4),
  ('00000000-0000-4000-9002-000000000006', '00000000-0000-4000-8000-000000000002', 'Head Shave', 'Clean full head shave with hot lather and aftercare.', 'Hair', 30, 6500, 'SAR', 0, false, 5);
insert into public.staff (id, venue_id, name, role, rating) values
  ('00000000-0000-4000-a002-000000000001', '00000000-0000-4000-8000-000000000002', 'Omar', 'Master barber', 5),
  ('00000000-0000-4000-a002-000000000002', '00000000-0000-4000-8000-000000000002', 'Khalid', 'Barber', 4.8),
  ('00000000-0000-4000-a002-000000000003', '00000000-0000-4000-8000-000000000002', 'Marco', 'Senior barber', 4.8999999999999995);
insert into public.reviews (id, venue_id, author_name, rating, comment, created_at) values
  ('00000000-0000-4000-b002-000000000001', '00000000-0000-4000-8000-000000000002', 'Reem K', 4, 'Great service and lovely atmosphere. Slightly busy on weekends but worth it.', '2026-03-04T10:00:00Z'),
  ('00000000-0000-4000-b002-000000000002', '00000000-0000-4000-8000-000000000002', 'Aisha B', 4, 'Very professional team and beautiful interior. Will definitely come back.', '2026-03-09T11:00:00Z'),
  ('00000000-0000-4000-b002-000000000003', '00000000-0000-4000-8000-000000000002', 'Sara A', 5, 'Amazing experience from start to finish. The team is so welcoming and the results were perfect.', '2026-03-14T12:00:00Z'),
  ('00000000-0000-4000-b002-000000000004', '00000000-0000-4000-8000-000000000002', 'Lina H', 5, 'Absolutely in love with the results. Professional, clean and friendly staff.', '2026-03-19T13:00:00Z'),
  ('00000000-0000-4000-b002-000000000005', '00000000-0000-4000-8000-000000000002', 'Maha S', 5, 'Effortless booking and outstanding service. Highly recommend to everyone.', '2026-03-24T14:00:00Z'),
  ('00000000-0000-4000-b002-000000000006', '00000000-0000-4000-8000-000000000002', 'Norah M', 5, 'Best booking experience I have had. Walked in and everything was ready for me.', '2026-03-02T15:00:00Z');
insert into public.opening_hours (venue_id, weekday, open_time, close_time, is_closed) values
  ('00000000-0000-4000-8000-000000000002', 0, null, null, true),
  ('00000000-0000-4000-8000-000000000002', 1, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000002', 2, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000002', 3, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000002', 4, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000002', 5, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000002', 6, '10:00', '22:00', false);

insert into public.venues (id, slug, name, description, category_id, address, area, city, country, rating_avg, rating_count, is_featured, is_new, is_trending, highlights) values
  ('00000000-0000-4000-8000-000000000003', 'the-blowout-bar', 'The Blowout Bar', 'Jeddah’s destination for perfect hair, fast. Signature blowouts, glossy styling, braids and treatments - walk in polished, walk out camera-ready.', 1, 'Prince Faisal Bin Fahd Rd', 'Ash Shati', 'Jeddah', 'Saudi Arabia', 4.7, 151, true, false, false, array['Instant confirmation', 'Walk-ins welcome', 'Parking available']::text[]);
insert into public.venue_images (venue_id, url, sort_order) values
  ('00000000-0000-4000-8000-000000000003', 'https://images.unsplash.com/photo-1600948836101-f9ffda59d250?w=1200&q=80&auto=format&fit=crop', 0),
  ('00000000-0000-4000-8000-000000000003', 'https://images.unsplash.com/photo-1500840216050-6ffa99d75160?w=1200&q=80&auto=format&fit=crop', 1),
  ('00000000-0000-4000-8000-000000000003', 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=1200&q=80&auto=format&fit=crop', 2);
insert into public.services (id, venue_id, name, description, group_name, duration_minutes, price_cents, currency, discount_pct, is_featured, sort_order) values
  ('00000000-0000-4000-9003-000000000001', '00000000-0000-4000-8000-000000000003', 'Signature Blowout', 'Wash, blow dry and finish - smooth, bouncy or beach waves.', 'Featured', 45, 14000, 'SAR', 0, true, 0),
  ('00000000-0000-4000-9003-000000000002', '00000000-0000-4000-8000-000000000003', 'Express Blowout', 'In a rush? Dry styling in half an hour.', 'Featured', 30, 10000, 'SAR', 0, true, 1),
  ('00000000-0000-4000-9003-000000000003', '00000000-0000-4000-8000-000000000003', 'Glass Hair Gloss', 'High-shine gloss treatment with sleek finish.', 'Styling', 60, 22000, 'SAR', 0, false, 2),
  ('00000000-0000-4000-9003-000000000004', '00000000-0000-4000-8000-000000000003', 'Braided Updo', 'Event-ready braids and updos by our stylists.', 'Styling', 60, 18000, 'SAR', 0, false, 3),
  ('00000000-0000-4000-9003-000000000005', '00000000-0000-4000-8000-000000000003', 'Deep Repair Treatment', 'Intense mask and scalp massage for tired hair.', 'Treatments', 45, 16000, 'SAR', 0, false, 4),
  ('00000000-0000-4000-9003-000000000006', '00000000-0000-4000-8000-000000000003', 'Silk Press', 'Smooth, natural silk press with heat protection.', 'Styling', 90, 28000, 'SAR', 0, false, 5);
insert into public.staff (id, venue_id, name, role, rating) values
  ('00000000-0000-4000-a003-000000000001', '00000000-0000-4000-8000-000000000003', 'Anong', 'Senior stylist', 4.8),
  ('00000000-0000-4000-a003-000000000002', '00000000-0000-4000-8000-000000000003', 'Mei', 'Stylist', 4.8999999999999995),
  ('00000000-0000-4000-a003-000000000003', '00000000-0000-4000-8000-000000000003', 'Priya', 'Stylist', 5);
insert into public.reviews (id, venue_id, author_name, rating, comment, created_at) values
  ('00000000-0000-4000-b003-000000000001', '00000000-0000-4000-8000-000000000003', 'Lina H', 5, 'Absolutely in love with the results. Professional, clean and friendly staff.', '2026-04-04T10:00:00Z'),
  ('00000000-0000-4000-b003-000000000002', '00000000-0000-4000-8000-000000000003', 'Maha S', 5, 'Effortless booking and outstanding service. Highly recommend to everyone.', '2026-04-09T11:00:00Z'),
  ('00000000-0000-4000-b003-000000000003', '00000000-0000-4000-8000-000000000003', 'Norah M', 5, 'Best booking experience I have had. Walked in and everything was ready for me.', '2026-04-14T12:00:00Z'),
  ('00000000-0000-4000-b003-000000000004', '00000000-0000-4000-8000-000000000003', 'Dana F', 5, 'My go-to place now. The attention to detail is unmatched.', '2026-04-19T13:00:00Z');
insert into public.opening_hours (venue_id, weekday, open_time, close_time, is_closed) values
  ('00000000-0000-4000-8000-000000000003', 0, null, null, true),
  ('00000000-0000-4000-8000-000000000003', 1, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000003', 2, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000003', 3, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000003', 4, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000003', 5, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000003', 6, '10:00', '22:00', false);

insert into public.venues (id, slug, name, description, category_id, address, area, city, country, rating_avg, rating_count, is_featured, is_new, is_trending, highlights) values
  ('00000000-0000-4000-8000-000000000004', 'velvet-nails-lounge', 'Velvet Nails Lounge', 'Luxury nail artistry in the heart of Riyadh. From flawless gel manicures to bespoke nail art, our masters treat every set as a canvas.', 3, 'Olaya Towers, Tahlia St', 'Al Olaya', 'Riyadh', 'Saudi Arabia', 4.9, 188, true, false, false, array['Instant confirmation', 'Pay by app', 'Woman-owned', 'Adults only']::text[]);
insert into public.venue_images (venue_id, url, sort_order) values
  ('00000000-0000-4000-8000-000000000004', 'https://images.unsplash.com/photo-1583209814683-c023dd293cc6?w=1200&q=80&auto=format&fit=crop', 0),
  ('00000000-0000-4000-8000-000000000004', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=1200&q=80&auto=format&fit=crop', 1),
  ('00000000-0000-4000-8000-000000000004', 'https://images.unsplash.com/photo-1633681926022-84c23e8cb2d6?w=1200&q=80&auto=format&fit=crop', 2);
insert into public.services (id, venue_id, name, description, group_name, duration_minutes, price_cents, currency, discount_pct, is_featured, sort_order) values
  ('00000000-0000-4000-9004-000000000001', '00000000-0000-4000-8000-000000000004', 'Gel Manicure', 'Long-lasting gel polish with meticulous cuticle care and shaping.', 'Featured', 60, 15000, 'SAR', 0, true, 0),
  ('00000000-0000-4000-9004-000000000002', '00000000-0000-4000-8000-000000000004', 'Luxury Spa Pedicure', 'A pampering pedicure with sugar scrub, mask and hot towels.', 'Featured', 75, 20000, 'SAR', 15, true, 1),
  ('00000000-0000-4000-9004-000000000003', '00000000-0000-4000-8000-000000000004', 'Nail Art (per nail)', 'Hand-painted designs, chrome, foils and crystals.', 'Nail Art', 10, 1500, 'SAR', 0, false, 2),
  ('00000000-0000-4000-9004-000000000004', '00000000-0000-4000-8000-000000000004', 'Gel Removal', 'Gentle soak-off removal that protects your natural nail.', 'Nails', 20, 4000, 'SAR', 0, false, 3),
  ('00000000-0000-4000-9004-000000000005', '00000000-0000-4000-8000-000000000004', 'Classic Manicure', 'Shape, buff, cuticle care and classic polish.', 'Nails', 45, 9000, 'SAR', 0, false, 4),
  ('00000000-0000-4000-9004-000000000006', '00000000-0000-4000-8000-000000000004', 'BIAB Overlay', 'Builder gel overlay for stronger natural nails.', 'Nails', 75, 18000, 'SAR', 0, false, 5);
insert into public.staff (id, venue_id, name, role, rating) values
  ('00000000-0000-4000-a004-000000000001', '00000000-0000-4000-8000-000000000004', 'Jenny', 'Nail artist', 4.8999999999999995),
  ('00000000-0000-4000-a004-000000000002', '00000000-0000-4000-8000-000000000004', 'Thao', 'Senior nail tech', 5),
  ('00000000-0000-4000-a004-000000000003', '00000000-0000-4000-8000-000000000004', 'Rania', 'Nail tech', 4.8);
insert into public.reviews (id, venue_id, author_name, rating, comment, created_at) values
  ('00000000-0000-4000-b004-000000000001', '00000000-0000-4000-8000-000000000004', 'Dana F', 5, 'My go-to place now. The attention to detail is unmatched.', '2026-05-04T10:00:00Z'),
  ('00000000-0000-4000-b004-000000000002', '00000000-0000-4000-8000-000000000004', 'Yara T', 5, 'The staff really listen to what you want. Left feeling brand new!', '2026-05-09T11:00:00Z'),
  ('00000000-0000-4000-b004-000000000003', '00000000-0000-4000-8000-000000000004', 'Reem K', 4, 'Great service and lovely atmosphere. Slightly busy on weekends but worth it.', '2026-05-14T12:00:00Z'),
  ('00000000-0000-4000-b004-000000000004', '00000000-0000-4000-8000-000000000004', 'Aisha B', 4, 'Very professional team and beautiful interior. Will definitely come back.', '2026-05-19T13:00:00Z'),
  ('00000000-0000-4000-b004-000000000005', '00000000-0000-4000-8000-000000000004', 'Sara A', 5, 'Amazing experience from start to finish. The team is so welcoming and the results were perfect.', '2026-05-24T14:00:00Z');
insert into public.opening_hours (venue_id, weekday, open_time, close_time, is_closed) values
  ('00000000-0000-4000-8000-000000000004', 0, null, null, true),
  ('00000000-0000-4000-8000-000000000004', 1, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000004', 2, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000004', 3, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000004', 4, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000004', 5, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000004', 6, '10:00', '22:00', false);

insert into public.venues (id, slug, name, description, category_id, address, area, city, country, rating_avg, rating_count, is_featured, is_new, is_trending, highlights) values
  ('00000000-0000-4000-8000-000000000005', 'marble-and-mane', 'Marble & Mane Hair Studio', 'A destination hair studio for cuts, colour and transformations. Our stylists train internationally and specialise in balayage, precision cutting and healthy-hair treatments.', 1, 'Prince Turki Al Awwal Rd', 'Hittin', 'Riyadh', 'Saudi Arabia', 4.6, 225, true, false, false, array['Instant confirmation', 'Pay by app', 'Complimentary drinks']::text[]);
insert into public.venue_images (venue_id, url, sort_order) values
  ('00000000-0000-4000-8000-000000000005', 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&q=80&auto=format&fit=crop', 0),
  ('00000000-0000-4000-8000-000000000005', 'https://images.unsplash.com/photo-1600948836101-f9ffda59d250?w=1200&q=80&auto=format&fit=crop', 1),
  ('00000000-0000-4000-8000-000000000005', 'https://images.unsplash.com/photo-1633681926022-84c23e8cb2d6?w=1200&q=80&auto=format&fit=crop', 2);
insert into public.services (id, venue_id, name, description, group_name, duration_minutes, price_cents, currency, discount_pct, is_featured, sort_order) values
  ('00000000-0000-4000-9005-000000000001', '00000000-0000-4000-8000-000000000005', 'Cut & Blow Dry', 'Consultation, precision cut and a bouncy blow dry finish.', 'Featured', 60, 18000, 'SAR', 0, true, 0),
  ('00000000-0000-4000-9005-000000000002', '00000000-0000-4000-8000-000000000005', 'Full Balayage', 'Hand-painted colour melt with toner and treatment.', 'Featured', 180, 75000, 'SAR', 10, true, 1),
  ('00000000-0000-4000-9005-000000000003', '00000000-0000-4000-8000-000000000005', 'Root Colour', 'Full root coverage with premium ammonia-free colour.', 'Colour', 90, 30000, 'SAR', 0, false, 2),
  ('00000000-0000-4000-9005-000000000004', '00000000-0000-4000-8000-000000000005', 'Keratin Smoothing', 'Frizz-free, glossy hair for up to 4 months.', 'Treatments', 150, 60000, 'SAR', 0, false, 3),
  ('00000000-0000-4000-9005-000000000005', '00000000-0000-4000-8000-000000000005', 'Olaplex Repair Ritual', 'Bond-building treatment for stronger, healthier hair.', 'Treatments', 45, 20000, 'SAR', 0, false, 4),
  ('00000000-0000-4000-9005-000000000006', '00000000-0000-4000-8000-000000000005', 'Bridal Hair Trial', 'Full bridal styling session with our senior stylist.', 'Styling', 90, 35000, 'SAR', 0, false, 5);
insert into public.staff (id, venue_id, name, role, rating) values
  ('00000000-0000-4000-a005-000000000001', '00000000-0000-4000-8000-000000000005', 'Elena', 'Creative director', 5),
  ('00000000-0000-4000-a005-000000000002', '00000000-0000-4000-8000-000000000005', 'Sophie', 'Colour specialist', 4.8),
  ('00000000-0000-4000-a005-000000000003', '00000000-0000-4000-8000-000000000005', 'Amir', 'Senior stylist', 4.8999999999999995);
insert into public.reviews (id, venue_id, author_name, rating, comment, created_at) values
  ('00000000-0000-4000-b005-000000000001', '00000000-0000-4000-8000-000000000005', 'Aisha B', 4, 'Very professional team and beautiful interior. Will definitely come back.', '2026-06-04T10:00:00Z'),
  ('00000000-0000-4000-b005-000000000002', '00000000-0000-4000-8000-000000000005', 'Sara A', 5, 'Amazing experience from start to finish. The team is so welcoming and the results were perfect.', '2026-06-09T11:00:00Z'),
  ('00000000-0000-4000-b005-000000000003', '00000000-0000-4000-8000-000000000005', 'Lina H', 5, 'Absolutely in love with the results. Professional, clean and friendly staff.', '2026-06-14T12:00:00Z'),
  ('00000000-0000-4000-b005-000000000004', '00000000-0000-4000-8000-000000000005', 'Maha S', 5, 'Effortless booking and outstanding service. Highly recommend to everyone.', '2026-06-19T13:00:00Z'),
  ('00000000-0000-4000-b005-000000000005', '00000000-0000-4000-8000-000000000005', 'Norah M', 5, 'Best booking experience I have had. Walked in and everything was ready for me.', '2026-06-24T14:00:00Z'),
  ('00000000-0000-4000-b005-000000000006', '00000000-0000-4000-8000-000000000005', 'Dana F', 5, 'My go-to place now. The attention to detail is unmatched.', '2026-06-02T15:00:00Z');
insert into public.opening_hours (venue_id, weekday, open_time, close_time, is_closed) values
  ('00000000-0000-4000-8000-000000000005', 0, null, null, true),
  ('00000000-0000-4000-8000-000000000005', 1, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000005', 2, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000005', 3, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000005', 4, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000005', 5, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000005', 6, '10:00', '22:00', false);

insert into public.venues (id, slug, name, description, category_id, address, area, city, country, rating_avg, rating_count, is_featured, is_new, is_trending, highlights) values
  ('00000000-0000-4000-8000-000000000006', 'pure-skin-studio', 'Pure Skin Studio', 'A skincare salon devoted to the glow: deep-cleansing facials, gentle peels, dermaplaning and LED - tailored to your skin by certified estheticians.', 6, 'Prince Sultan Rd', 'Al Hamra', 'Jeddah', 'Saudi Arabia', 4.8, 262, false, true, false, array['Instant confirmation', 'Certified estheticians', 'Parking available']::text[]);
insert into public.venue_images (venue_id, url, sort_order) values
  ('00000000-0000-4000-8000-000000000006', 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=1200&q=80&auto=format&fit=crop', 0),
  ('00000000-0000-4000-8000-000000000006', 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80&auto=format&fit=crop', 1),
  ('00000000-0000-4000-8000-000000000006', 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=1200&q=80&auto=format&fit=crop', 2);
insert into public.services (id, venue_id, name, description, group_name, duration_minutes, price_cents, currency, discount_pct, is_featured, sort_order) values
  ('00000000-0000-4000-9006-000000000001', '00000000-0000-4000-8000-000000000006', 'Signature Glow Facial', 'Deep cleanse, exfoliation, extraction and hydration boost.', 'Featured', 60, 30000, 'SAR', 0, true, 0),
  ('00000000-0000-4000-9006-000000000002', '00000000-0000-4000-8000-000000000006', 'HydraFacial Deluxe', 'Deep cleanse, exfoliation, extraction and antioxidant infusion.', 'Featured', 60, 45000, 'SAR', 0, true, 1),
  ('00000000-0000-4000-9006-000000000003', '00000000-0000-4000-8000-000000000006', 'Gentle Enzyme Peel', 'Brightening peel customised to your skin goals.', 'Skin', 45, 25000, 'SAR', 0, false, 2),
  ('00000000-0000-4000-9006-000000000004', '00000000-0000-4000-8000-000000000006', 'Dermaplaning + Mask', 'Smooth, peach-fuzz-free skin with a soothing finish mask.', 'Skin', 45, 22000, 'SAR', 0, false, 3),
  ('00000000-0000-4000-9006-000000000005', '00000000-0000-4000-8000-000000000006', 'LED Light Therapy', 'Calming, collagen-boosting LED session.', 'Skin', 30, 15000, 'SAR', 0, false, 4);
insert into public.staff (id, venue_id, name, role, rating) values
  ('00000000-0000-4000-a006-000000000001', '00000000-0000-4000-8000-000000000006', 'Hala', 'Lead esthetician', 4.8),
  ('00000000-0000-4000-a006-000000000002', '00000000-0000-4000-8000-000000000006', 'Nour', 'Esthetician', 4.8999999999999995),
  ('00000000-0000-4000-a006-000000000003', '00000000-0000-4000-8000-000000000006', 'Farah', 'Esthetician', 5);
insert into public.reviews (id, venue_id, author_name, rating, comment, created_at) values
  ('00000000-0000-4000-b006-000000000001', '00000000-0000-4000-8000-000000000006', 'Maha S', 5, 'Effortless booking and outstanding service. Highly recommend to everyone.', '2026-01-04T10:00:00Z'),
  ('00000000-0000-4000-b006-000000000002', '00000000-0000-4000-8000-000000000006', 'Norah M', 5, 'Best booking experience I have had. Walked in and everything was ready for me.', '2026-01-09T11:00:00Z'),
  ('00000000-0000-4000-b006-000000000003', '00000000-0000-4000-8000-000000000006', 'Dana F', 5, 'My go-to place now. The attention to detail is unmatched.', '2026-01-14T12:00:00Z'),
  ('00000000-0000-4000-b006-000000000004', '00000000-0000-4000-8000-000000000006', 'Yara T', 5, 'The staff really listen to what you want. Left feeling brand new!', '2026-01-19T13:00:00Z');
insert into public.opening_hours (venue_id, weekday, open_time, close_time, is_closed) values
  ('00000000-0000-4000-8000-000000000006', 0, null, null, true),
  ('00000000-0000-4000-8000-000000000006', 1, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000006', 2, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000006', 3, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000006', 4, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000006', 5, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000006', 6, '10:00', '22:00', false);

insert into public.venues (id, slug, name, description, category_id, address, area, city, country, rating_avg, rating_count, is_featured, is_new, is_trending, highlights) values
  ('00000000-0000-4000-8000-000000000007', 'the-nail-atelier', 'The Nail Atelier', 'A boutique nail studio where minimalist design meets meticulous craft. Specialists in Russian manicure, BIAB and editorial nail art.', 3, 'Anas Ibn Malik Rd', 'Al Malqa', 'Riyadh', 'Saudi Arabia', 5, 299, false, true, false, array['Instant confirmation', 'Woman-owned', 'By appointment only']::text[]);
insert into public.venue_images (venue_id, url, sort_order) values
  ('00000000-0000-4000-8000-000000000007', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=1200&q=80&auto=format&fit=crop', 0),
  ('00000000-0000-4000-8000-000000000007', 'https://images.unsplash.com/photo-1583209814683-c023dd293cc6?w=1200&q=80&auto=format&fit=crop', 1),
  ('00000000-0000-4000-8000-000000000007', 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80&auto=format&fit=crop', 2);
insert into public.services (id, venue_id, name, description, group_name, duration_minutes, price_cents, currency, discount_pct, is_featured, sort_order) values
  ('00000000-0000-4000-9007-000000000001', '00000000-0000-4000-8000-000000000007', 'Russian Manicure + Gel', 'Ultra-precise dry manicure with flawless gel application.', 'Featured', 90, 22000, 'SAR', 0, true, 0),
  ('00000000-0000-4000-9007-000000000002', '00000000-0000-4000-8000-000000000007', 'BIAB Natural Overlay', 'Strengthen and grow your natural nails with builder gel.', 'Featured', 75, 19000, 'SAR', 0, true, 1),
  ('00000000-0000-4000-9007-000000000003', '00000000-0000-4000-8000-000000000007', 'Pedicure + Gel', 'Complete pedicure with long-wear gel polish.', 'Pedicure', 90, 24000, 'SAR', 0, false, 2),
  ('00000000-0000-4000-9007-000000000004', '00000000-0000-4000-8000-000000000007', 'French Tips', 'Timeless hand-painted french in any shade.', 'Nail Art', 30, 6000, 'SAR', 0, false, 3),
  ('00000000-0000-4000-9007-000000000005', '00000000-0000-4000-8000-000000000007', 'Nail Repair (per nail)', 'Crack and break repair that blends invisibly.', 'Nails', 15, 2000, 'SAR', 0, false, 4);
insert into public.staff (id, venue_id, name, role, rating) values
  ('00000000-0000-4000-a007-000000000001', '00000000-0000-4000-8000-000000000007', 'Kateryna', 'Master nail artist', 4.8999999999999995),
  ('00000000-0000-4000-a007-000000000002', '00000000-0000-4000-8000-000000000007', 'Alina', 'Nail artist', 5),
  ('00000000-0000-4000-a007-000000000003', '00000000-0000-4000-8000-000000000007', 'Joud', 'Nail tech', 4.8);
insert into public.reviews (id, venue_id, author_name, rating, comment, created_at) values
  ('00000000-0000-4000-b007-000000000001', '00000000-0000-4000-8000-000000000007', 'Yara T', 5, 'The staff really listen to what you want. Left feeling brand new!', '2026-02-04T10:00:00Z'),
  ('00000000-0000-4000-b007-000000000002', '00000000-0000-4000-8000-000000000007', 'Reem K', 4, 'Great service and lovely atmosphere. Slightly busy on weekends but worth it.', '2026-02-09T11:00:00Z'),
  ('00000000-0000-4000-b007-000000000003', '00000000-0000-4000-8000-000000000007', 'Aisha B', 4, 'Very professional team and beautiful interior. Will definitely come back.', '2026-02-14T12:00:00Z'),
  ('00000000-0000-4000-b007-000000000004', '00000000-0000-4000-8000-000000000007', 'Sara A', 5, 'Amazing experience from start to finish. The team is so welcoming and the results were perfect.', '2026-02-19T13:00:00Z'),
  ('00000000-0000-4000-b007-000000000005', '00000000-0000-4000-8000-000000000007', 'Lina H', 5, 'Absolutely in love with the results. Professional, clean and friendly staff.', '2026-02-24T14:00:00Z');
insert into public.opening_hours (venue_id, weekday, open_time, close_time, is_closed) values
  ('00000000-0000-4000-8000-000000000007', 0, null, null, true),
  ('00000000-0000-4000-8000-000000000007', 1, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000007', 2, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000007', 3, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000007', 4, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000007', 5, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000007', 6, '10:00', '22:00', false);

insert into public.venues (id, slug, name, description, category_id, address, area, city, country, rating_avg, rating_count, is_featured, is_new, is_trending, highlights) values
  ('00000000-0000-4000-8000-000000000008', 'smooth-and-co-waxing', 'Smooth & Co Waxing Salon', 'The waxing specialists. Gentle low-temperature wax, spotless private rooms and therapists who make it quick, clean and comfortable.', 5, 'Prince Mohammed Bin Fahd Rd', 'Ash Shati', 'Dammam', 'Saudi Arabia', 4.7, 336, false, true, false, array['Instant confirmation', 'Pay by app', 'Private rooms', 'Woman-owned']::text[]);
insert into public.venue_images (venue_id, url, sort_order) values
  ('00000000-0000-4000-8000-000000000008', 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=1200&q=80&auto=format&fit=crop', 0),
  ('00000000-0000-4000-8000-000000000008', 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80&auto=format&fit=crop', 1),
  ('00000000-0000-4000-8000-000000000008', 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=1200&q=80&auto=format&fit=crop', 2);
insert into public.services (id, venue_id, name, description, group_name, duration_minutes, price_cents, currency, discount_pct, is_featured, sort_order) values
  ('00000000-0000-4000-9008-000000000001', '00000000-0000-4000-8000-000000000008', 'Full Body Wax', 'Head-to-toe smoothness with gentle, low-temp wax.', 'Featured', 90, 32000, 'SAR', 0, true, 0),
  ('00000000-0000-4000-9008-000000000002', '00000000-0000-4000-8000-000000000008', 'Full Legs Wax', 'Silky legs in under an hour.', 'Featured', 40, 14000, 'SAR', 0, true, 1),
  ('00000000-0000-4000-9008-000000000003', '00000000-0000-4000-8000-000000000008', 'Underarm Wax', 'Quick and gentle underarm waxing.', 'Waxing', 15, 5000, 'SAR', 0, false, 2),
  ('00000000-0000-4000-9008-000000000004', '00000000-0000-4000-8000-000000000008', 'Full Arms Wax', 'Complete arm waxing with soothing aftercare.', 'Waxing', 30, 10000, 'SAR', 0, false, 3),
  ('00000000-0000-4000-9008-000000000005', '00000000-0000-4000-8000-000000000008', 'Full Face Threading', 'Precise full-face hair removal with thread.', 'Threading', 30, 9000, 'SAR', 0, false, 4);
insert into public.staff (id, venue_id, name, role, rating) values
  ('00000000-0000-4000-a008-000000000001', '00000000-0000-4000-8000-000000000008', 'Grace', 'Wax specialist', 5),
  ('00000000-0000-4000-a008-000000000002', '00000000-0000-4000-8000-000000000008', 'Marta', 'Wax specialist', 4.8),
  ('00000000-0000-4000-a008-000000000003', '00000000-0000-4000-8000-000000000008', 'Ivy', 'Therapist', 4.8999999999999995);
insert into public.reviews (id, venue_id, author_name, rating, comment, created_at) values
  ('00000000-0000-4000-b008-000000000001', '00000000-0000-4000-8000-000000000008', 'Sara A', 5, 'Amazing experience from start to finish. The team is so welcoming and the results were perfect.', '2026-03-04T10:00:00Z'),
  ('00000000-0000-4000-b008-000000000002', '00000000-0000-4000-8000-000000000008', 'Lina H', 5, 'Absolutely in love with the results. Professional, clean and friendly staff.', '2026-03-09T11:00:00Z'),
  ('00000000-0000-4000-b008-000000000003', '00000000-0000-4000-8000-000000000008', 'Maha S', 5, 'Effortless booking and outstanding service. Highly recommend to everyone.', '2026-03-14T12:00:00Z'),
  ('00000000-0000-4000-b008-000000000004', '00000000-0000-4000-8000-000000000008', 'Norah M', 5, 'Best booking experience I have had. Walked in and everything was ready for me.', '2026-03-19T13:00:00Z'),
  ('00000000-0000-4000-b008-000000000005', '00000000-0000-4000-8000-000000000008', 'Dana F', 5, 'My go-to place now. The attention to detail is unmatched.', '2026-03-24T14:00:00Z'),
  ('00000000-0000-4000-b008-000000000006', '00000000-0000-4000-8000-000000000008', 'Yara T', 5, 'The staff really listen to what you want. Left feeling brand new!', '2026-03-02T15:00:00Z');
insert into public.opening_hours (venue_id, weekday, open_time, close_time, is_closed) values
  ('00000000-0000-4000-8000-000000000008', 0, null, null, true),
  ('00000000-0000-4000-8000-000000000008', 1, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000008', 2, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000008', 3, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000008', 4, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000008', 5, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000008', 6, '10:00', '22:00', false);

insert into public.venues (id, slug, name, description, category_id, address, area, city, country, rating_avg, rating_count, is_featured, is_new, is_trending, highlights) values
  ('00000000-0000-4000-8000-000000000010', 'the-glam-room', 'The Glam Room', 'Jeddah’s go-to makeup studio for events, weddings and photoshoots. Senior artists, premium products and a look that lasts all night.', 7, 'North Corniche Rd', 'Corniche', 'Jeddah', 'Saudi Arabia', 4.6, 410, false, false, true, array['Instant confirmation', 'Sea view', 'Parking available', 'Woman-owned']::text[]);
insert into public.venue_images (venue_id, url, sort_order) values
  ('00000000-0000-4000-8000-000000000010', 'https://images.unsplash.com/photo-1500840216050-6ffa99d75160?w=1200&q=80&auto=format&fit=crop', 0),
  ('00000000-0000-4000-8000-000000000010', 'https://images.unsplash.com/photo-1583209814683-c023dd293cc6?w=1200&q=80&auto=format&fit=crop', 1),
  ('00000000-0000-4000-8000-000000000010', 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=1200&q=80&auto=format&fit=crop', 2);
insert into public.services (id, venue_id, name, description, group_name, duration_minutes, price_cents, currency, discount_pct, is_featured, sort_order) values
  ('00000000-0000-4000-9010-000000000001', '00000000-0000-4000-8000-000000000010', 'Full Glam Makeup', 'Occasion-ready full face by our senior artists.', 'Featured', 75, 40000, 'SAR', 0, true, 0),
  ('00000000-0000-4000-9010-000000000002', '00000000-0000-4000-8000-000000000010', 'Soft Glam Makeup', 'Natural, radiant makeup for daytime events.', 'Featured', 60, 30000, 'SAR', 0, true, 1),
  ('00000000-0000-4000-9010-000000000003', '00000000-0000-4000-8000-000000000010', 'Bridal Makeup Trial', 'Try your wedding look before the big day.', 'Bridal', 90, 45000, 'SAR', 0, false, 2),
  ('00000000-0000-4000-9010-000000000004', '00000000-0000-4000-8000-000000000010', 'Makeup Lesson (1:1)', 'Personal masterclass with your own products.', 'Lessons', 90, 50000, 'SAR', 0, false, 3);
insert into public.staff (id, venue_id, name, role, rating) values
  ('00000000-0000-4000-a010-000000000001', '00000000-0000-4000-8000-000000000010', 'Layla', 'Senior makeup artist', 4.8999999999999995),
  ('00000000-0000-4000-a010-000000000002', '00000000-0000-4000-8000-000000000010', 'Kim', 'Makeup artist', 5),
  ('00000000-0000-4000-a010-000000000003', '00000000-0000-4000-8000-000000000010', 'Amani', 'Makeup artist', 4.8);
insert into public.reviews (id, venue_id, author_name, rating, comment, created_at) values
  ('00000000-0000-4000-b010-000000000001', '00000000-0000-4000-8000-000000000010', 'Reem K', 4, 'Great service and lovely atmosphere. Slightly busy on weekends but worth it.', '2026-05-04T10:00:00Z'),
  ('00000000-0000-4000-b010-000000000002', '00000000-0000-4000-8000-000000000010', 'Aisha B', 4, 'Very professional team and beautiful interior. Will definitely come back.', '2026-05-09T11:00:00Z'),
  ('00000000-0000-4000-b010-000000000003', '00000000-0000-4000-8000-000000000010', 'Sara A', 5, 'Amazing experience from start to finish. The team is so welcoming and the results were perfect.', '2026-05-14T12:00:00Z'),
  ('00000000-0000-4000-b010-000000000004', '00000000-0000-4000-8000-000000000010', 'Lina H', 5, 'Absolutely in love with the results. Professional, clean and friendly staff.', '2026-05-19T13:00:00Z'),
  ('00000000-0000-4000-b010-000000000005', '00000000-0000-4000-8000-000000000010', 'Maha S', 5, 'Effortless booking and outstanding service. Highly recommend to everyone.', '2026-05-24T14:00:00Z');
insert into public.opening_hours (venue_id, weekday, open_time, close_time, is_closed) values
  ('00000000-0000-4000-8000-000000000010', 0, null, null, true),
  ('00000000-0000-4000-8000-000000000010', 1, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000010', 2, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000010', 3, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000010', 4, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000010', 5, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000010', 6, '10:00', '22:00', false);

insert into public.venues (id, slug, name, description, category_id, address, area, city, country, rating_avg, rating_count, is_featured, is_new, is_trending, highlights) values
  ('00000000-0000-4000-8000-000000000011', 'gentlemens-quarter', 'Gentlemen''s Quarter', 'Riyadh’s premium grooming lounge: sharp cuts, royal shaves, facials for men and a complimentary espresso bar.', 2, 'King Fahd Rd', 'King Fahd District', 'Riyadh', 'Saudi Arabia', 4.8, 447, false, false, true, array['Instant confirmation', 'Pay by app', 'Espresso bar']::text[]);
insert into public.venue_images (venue_id, url, sort_order) values
  ('00000000-0000-4000-8000-000000000011', 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=1200&q=80&auto=format&fit=crop', 0),
  ('00000000-0000-4000-8000-000000000011', 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&q=80&auto=format&fit=crop', 1),
  ('00000000-0000-4000-8000-000000000011', 'https://images.unsplash.com/photo-1600948836101-f9ffda59d250?w=1200&q=80&auto=format&fit=crop', 2);
insert into public.services (id, venue_id, name, description, group_name, duration_minutes, price_cents, currency, discount_pct, is_featured, sort_order) values
  ('00000000-0000-4000-9011-000000000001', '00000000-0000-4000-8000-000000000011', 'Executive Cut & Style', 'Tailored cut, wash and style with premium finish.', 'Featured', 60, 15000, 'SAR', 0, true, 0),
  ('00000000-0000-4000-9011-000000000002', '00000000-0000-4000-8000-000000000011', 'Royal Shave', 'Hot towels, straight razor, facial massage - the full ritual.', 'Featured', 45, 11000, 'SAR', 0, true, 1),
  ('00000000-0000-4000-9011-000000000003', '00000000-0000-4000-8000-000000000011', 'Gentleman’s Facial', 'Deep-cleansing facial designed for men’s skin.', 'Grooming', 45, 18000, 'SAR', 0, false, 2),
  ('00000000-0000-4000-9011-000000000004', '00000000-0000-4000-8000-000000000011', 'Hair + Beard Combo', 'Complete grooming: cut, beard sculpt and style.', 'Hair', 75, 19000, 'SAR', 12, false, 3),
  ('00000000-0000-4000-9011-000000000005', '00000000-0000-4000-8000-000000000011', 'Grey Blending', 'Subtle, natural-looking grey coverage.', 'Colour', 45, 14000, 'SAR', 0, false, 4);
insert into public.staff (id, venue_id, name, role, rating) values
  ('00000000-0000-4000-a011-000000000001', '00000000-0000-4000-8000-000000000011', 'Hassan', 'Master barber', 5),
  ('00000000-0000-4000-a011-000000000002', '00000000-0000-4000-8000-000000000011', 'Tony', 'Senior barber', 4.8),
  ('00000000-0000-4000-a011-000000000003', '00000000-0000-4000-8000-000000000011', 'Youssef', 'Barber', 4.8999999999999995);
insert into public.reviews (id, venue_id, author_name, rating, comment, created_at) values
  ('00000000-0000-4000-b011-000000000001', '00000000-0000-4000-8000-000000000011', 'Lina H', 5, 'Absolutely in love with the results. Professional, clean and friendly staff.', '2026-06-04T10:00:00Z'),
  ('00000000-0000-4000-b011-000000000002', '00000000-0000-4000-8000-000000000011', 'Maha S', 5, 'Effortless booking and outstanding service. Highly recommend to everyone.', '2026-06-09T11:00:00Z'),
  ('00000000-0000-4000-b011-000000000003', '00000000-0000-4000-8000-000000000011', 'Norah M', 5, 'Best booking experience I have had. Walked in and everything was ready for me.', '2026-06-14T12:00:00Z'),
  ('00000000-0000-4000-b011-000000000004', '00000000-0000-4000-8000-000000000011', 'Dana F', 5, 'My go-to place now. The attention to detail is unmatched.', '2026-06-19T13:00:00Z'),
  ('00000000-0000-4000-b011-000000000005', '00000000-0000-4000-8000-000000000011', 'Yara T', 5, 'The staff really listen to what you want. Left feeling brand new!', '2026-06-24T14:00:00Z'),
  ('00000000-0000-4000-b011-000000000006', '00000000-0000-4000-8000-000000000011', 'Reem K', 4, 'Great service and lovely atmosphere. Slightly busy on weekends but worth it.', '2026-06-02T15:00:00Z');
insert into public.opening_hours (venue_id, weekday, open_time, close_time, is_closed) values
  ('00000000-0000-4000-8000-000000000011', 0, null, null, true),
  ('00000000-0000-4000-8000-000000000011', 1, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000011', 2, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000011', 3, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000011', 4, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000011', 5, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000011', 6, '10:00', '22:00', false);

insert into public.venues (id, slug, name, description, category_id, address, area, city, country, rating_avg, rating_count, is_featured, is_new, is_trending, highlights) values
  ('00000000-0000-4000-8000-000000000012', 'bloom-beauty-salon', 'Bloom Beauty Salon', 'Your everything salon: hair, makeup, nails and waxing under one roof. Trusted by Jeddah’s brides for over a decade.', 8, 'Sari St', 'Al Rawdah', 'Jeddah', 'Saudi Arabia', 5, 484, false, false, true, array['Instant confirmation', 'Woman-owned', 'Bridal packages']::text[]);
insert into public.venue_images (venue_id, url, sort_order) values
  ('00000000-0000-4000-8000-000000000012', 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=1200&q=80&auto=format&fit=crop', 0),
  ('00000000-0000-4000-8000-000000000012', 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80&auto=format&fit=crop', 1),
  ('00000000-0000-4000-8000-000000000012', 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=1200&q=80&auto=format&fit=crop', 2);
insert into public.services (id, venue_id, name, description, group_name, duration_minutes, price_cents, currency, discount_pct, is_featured, sort_order) values
  ('00000000-0000-4000-9012-000000000001', '00000000-0000-4000-8000-000000000012', 'Blow Dry & Style', 'Wash and professional blow dry, straight or curled.', 'Featured', 45, 12000, 'SAR', 0, true, 0),
  ('00000000-0000-4000-9012-000000000002', '00000000-0000-4000-8000-000000000012', 'Full Face Makeup', 'Occasion-ready glam by our senior makeup artists.', 'Featured', 60, 35000, 'SAR', 0, true, 1),
  ('00000000-0000-4000-9012-000000000003', '00000000-0000-4000-8000-000000000012', 'Hair Colour (full)', 'Full-head colour with gloss finish.', 'Colour', 120, 40000, 'SAR', 0, false, 2),
  ('00000000-0000-4000-9012-000000000004', '00000000-0000-4000-8000-000000000012', 'Full Body Wax', 'Complete waxing with gentle, low-temp wax.', 'Waxing', 90, 30000, 'SAR', 0, false, 3),
  ('00000000-0000-4000-9012-000000000005', '00000000-0000-4000-8000-000000000012', 'Bridal Package', 'Hair, makeup and nails for your big day.', 'Bridal', 240, 150000, 'SAR', 8, false, 4),
  ('00000000-0000-4000-9012-000000000006', '00000000-0000-4000-8000-000000000012', 'Hair Treatment Mask', 'Intense repair mask with scalp massage.', 'Treatments', 30, 10000, 'SAR', 0, false, 5);
insert into public.staff (id, venue_id, name, role, rating) values
  ('00000000-0000-4000-a012-000000000001', '00000000-0000-4000-8000-000000000012', 'Abeer', 'Salon director', 4.8),
  ('00000000-0000-4000-a012-000000000002', '00000000-0000-4000-8000-000000000012', 'Shatha', 'Makeup artist', 4.8999999999999995),
  ('00000000-0000-4000-a012-000000000003', '00000000-0000-4000-8000-000000000012', 'Noura', 'Stylist', 5);
insert into public.reviews (id, venue_id, author_name, rating, comment, created_at) values
  ('00000000-0000-4000-b012-000000000001', '00000000-0000-4000-8000-000000000012', 'Dana F', 5, 'My go-to place now. The attention to detail is unmatched.', '2026-01-04T10:00:00Z'),
  ('00000000-0000-4000-b012-000000000002', '00000000-0000-4000-8000-000000000012', 'Yara T', 5, 'The staff really listen to what you want. Left feeling brand new!', '2026-01-09T11:00:00Z'),
  ('00000000-0000-4000-b012-000000000003', '00000000-0000-4000-8000-000000000012', 'Reem K', 4, 'Great service and lovely atmosphere. Slightly busy on weekends but worth it.', '2026-01-14T12:00:00Z'),
  ('00000000-0000-4000-b012-000000000004', '00000000-0000-4000-8000-000000000012', 'Aisha B', 4, 'Very professional team and beautiful interior. Will definitely come back.', '2026-01-19T13:00:00Z');
insert into public.opening_hours (venue_id, weekday, open_time, close_time, is_closed) values
  ('00000000-0000-4000-8000-000000000012', 0, null, null, true),
  ('00000000-0000-4000-8000-000000000012', 1, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000012', 2, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000012', 3, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000012', 4, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000012', 5, '10:00', '22:00', false),
  ('00000000-0000-4000-8000-000000000012', 6, '10:00', '22:00', false);

insert into public.promo_codes (code, pct_off, is_active, expires_at) values
  ('WELCOME10', 10, true, null),
  ('BINK20', 20, true, '2026-12-31T23:59:59Z');

update public.venues v set rating_avg = coalesce((select round(avg(rating)::numeric, 2) from public.reviews r where r.venue_id = v.id), v.rating_avg);
