// Generates supabase/seed.sql and packages/shared/data/demo.json from scripts/data.mjs
// Run: node scripts/generate-seed.mjs
import { writeFileSync, mkdirSync } from 'node:fs';
import { buildData } from './data.mjs';

const { categories, venues, promos } = buildData();

const q = (s) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const arr = (a) => `array[${a.map(q).join(', ')}]::text[]`;

let sql = `-- Auto-generated by scripts/generate-seed.mjs. Do not edit by hand.\n\n`;

sql += `insert into public.categories (id, slug, name, icon, sort_order) values\n`;
sql += categories.map((c, i) => `  (${c.id}, ${q(c.slug)}, ${q(c.name)}, ${q(c.icon)}, ${i})`).join(',\n') + ';\n';
sql += `select setval('public.categories_id_seq', ${categories.length});\n\n`;

for (const v of venues) {
  sql += `insert into public.venues (id, slug, name, description, category_id, address, area, city, country, rating_avg, rating_count, is_featured, is_new, is_trending, highlights) values\n`;
  sql += `  (${q(v.id)}, ${q(v.slug)}, ${q(v.name)}, ${q(v.description)}, ${v.category_id}, ${q(v.address)}, ${q(v.area)}, ${q(v.city)}, ${q(v.country)}, ${v.rating_avg}, ${v.rating_count}, ${v.is_featured}, ${v.is_new}, ${v.is_trending}, ${arr(v.highlights)});\n`;

  sql += `insert into public.venue_images (venue_id, url, sort_order) values\n`;
  sql += v.images.map((im) => `  (${q(v.id)}, ${q(im.url)}, ${im.sort_order})`).join(',\n') + ';\n';

  sql += `insert into public.services (id, venue_id, name, description, group_name, duration_minutes, price_cents, currency, discount_pct, is_featured, sort_order) values\n`;
  sql += v.services.map((s) => `  (${q(s.id)}, ${q(v.id)}, ${q(s.name)}, ${q(s.description)}, ${q(s.group_name)}, ${s.duration_minutes}, ${s.price_cents}, ${q(s.currency)}, ${s.discount_pct}, ${s.is_featured}, ${s.sort_order})`).join(',\n') + ';\n';

  sql += `insert into public.staff (id, venue_id, name, role, rating) values\n`;
  sql += v.staff.map((s) => `  (${q(s.id)}, ${q(v.id)}, ${q(s.name)}, ${q(s.role)}, ${s.rating})`).join(',\n') + ';\n';

  sql += `insert into public.reviews (id, venue_id, author_name, rating, comment, created_at) values\n`;
  sql += v.reviews.map((r) => `  (${q(r.id)}, ${q(v.id)}, ${q(r.author_name)}, ${r.rating}, ${q(r.comment)}, ${q(r.created_at)})`).join(',\n') + ';\n';

  sql += `insert into public.opening_hours (venue_id, weekday, open_time, close_time, is_closed) values\n`;
  sql += v.hours.map((h) => `  (${q(v.id)}, ${h.weekday}, ${h.open_time ? q(h.open_time) : 'null'}, ${h.close_time ? q(h.close_time) : 'null'}, ${h.is_closed})`).join(',\n') + ';\n\n';
}

sql += `insert into public.promo_codes (code, pct_off, is_active, expires_at) values\n`;
sql += promos.map((p) => `  (${q(p.code)}, ${p.pct_off}, ${p.is_active}, ${p.expires_at ? q(p.expires_at) : 'null'})`).join(',\n') + ';\n\n';

// Seeded reviews carry hand-set aggregates; re-sync so venues reflect real rows
// while keeping the marketing-style counts (trigger already updated them).
sql += `update public.venues v set rating_avg = coalesce((select round(avg(rating)::numeric, 2) from public.reviews r where r.venue_id = v.id), v.rating_avg);\n`;

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql);

mkdirSync(new URL('../packages/shared/data', import.meta.url), { recursive: true });
writeFileSync(
  new URL('../packages/shared/data/demo.json', import.meta.url),
  JSON.stringify({ categories, venues, promos }, null, 2)
);

console.log(`Wrote supabase/seed.sql (${venues.length} venues) and packages/shared/data/demo.json`);
